### ISSUE TITLE
Professional license with a fallback to free

### ISSUE THREAD

**Issue by mikeage** [game-ci/unity-activate#60]
I'm using the game-ci github actions to build both formal releases and test PRs. Up to now, I've been using a free license stored in the yml, but I now have a professional license which I'd like to use to build my formal releases. However, since it's stored in a secret, it's not accessible by a PR from a fork.

Ideally, I'd like to be able to pass both the license file (in the yml) and the email/password/serial (from the secret), and if the email/password/serial is defined (i.e., the source is the main repo), it'd use those, but if not (e.g., a fork), it'd fall back to the free license. However, based on the order of the if / else if, it doesn't look like this will work.

Any ideas for how this can be done, or maybe a better workflow to use?

**Comment by davidmfinol** [comment]
One option is to have 2 workflows:
1) The main workflow would trigger `on: push` and use the email/password/serial
2) The second workflow would trigger `on: pull_request` and use the license

This isn't the cleanest option, though, as you would effectively have a lot of duplicate code between the two workflows. There may be another option using `if: {{ determine if running from pull request}}` on the build steps.

**Comment by mikeage** [comment]
True, but as you say, it's a lot of duplication. 

 I can do the if easily enough... but I don't think I can conditionally expose environment variables

**Comment by mikeage** [comment]
Ok, I think I have this working!

The following appears to work nicely:
```yaml
   UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
   UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
   UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
   UNITY_LICENSE: ${{ fromJSON('["FALLBACK_UNITY_LICENSE_ESCAPE_QUOTES_AND_ADD_BACKSLASH_N_FOR_NEWLINES", null]')[secrets.UNITY_SERIAL != null] }}
```

**Comment by starikcetin** [comment]
> 



> Ok, I think I have this working!
> 
> The following appears to work nicely:
> 
> ```yaml
>    UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
>    UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
>    UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
>    UNITY_LICENSE: ${{ fromJSON('["FALLBACK_UNITY_LICENSE_ESCAPE_QUOTES_AND_ADD_BACKSLASH_N_FOR_NEWLINES", null]')[secrets.UNITY_SERIAL != null] }}
> ```

Hello, @mikeage I am trying to understand how this falls back to a personal license. Would you mind giving some details?

**Comment by webbertakken** [comment]
That is because you're passing both a license and a serial.

You have to choose, one or the other. Or the action is forced to choose, in which case it chooses your personal license.

You can find the exact logic [here](https://github.com/game-ci/unity-activate/blob/33cd3ea96f11f3a1ddcf8fa9d8d265d5ea81e240/dist/entrypoint.sh#L13).

**Comment by mikeage** [comment]
Exactly :-)

**Comment by starikcetin** [comment]
So as far as I understand, with the example @mikeage has given the pro licence is not used at all, but instead, the personal licence is used always. Is that correct?

**Comment by webbertakken** [comment]
Exactly.

**Comment by mikeage** [comment]
So, my trick is that if the UNITY_SERIAL is defined, then it doesn't set the license at all. That's because the logic in the action prioritizes personal over professional, and I want to do the exact opposite.

(edit: deleted my earlier comment because it gave t wrong impression)

**Comment by mikeage** [comment]
Note the use of fromJSON and the index, which is basically a boolean, but also works as 0/1 for false/true respectively. I'm (ab)using the templating engine to effectively create a conditional assignment.

**Comment by webbertakken** [comment]
Why not just only only pass UNITY_SERIAL? and not pass UNITY_LICENSE?

This is actually quite confusing and not recommended by us.

**Comment by mikeage** [comment]
Because if I get a PR from a fork, they don't have access to the secrets (to prevent them from leaking), but I still want it to build. I'm happy to embed a free license in the yaml, but the pro license has to stay in secrets. But I want to use the pro license for release builds, which are from the same action with a different trigger.

**Comment by mikeage** [comment]
I can't think of any other case where someone would supply both and prefer the personal license, other than PRs with no access to the secrets vs PRs with access to secrets. As such, if you switched the order of the if / elif in the action, I'd just pass the license "straight".

Was that a deliberate design choice or just something that happened coincidentally? Am I missing another use case?

(btw, I'm going offline for about 24 hours in a few minutes so I won't be able to respond any more, but I'll be back)

**Comment by webbertakken** [comment]
#### Recommended solutions

The recommended approach here would be one of two:

- to duplicate the build job and add a condition for which trigger is used. 
- to create an additional job that determines both values based on which trigger is used. Then defining them like so:
```yaml
  env:
     UNITY_LICENSE: ${{ jobs.myJob.outputs.unityLicense }} # either empty or set
     UNITY_SERIAL: ${{ jobs.myJob.outputs.unitySerial }} # either empty or set
```

That way new developers can grasp what's going on.

#### Maybe changing the logic

Regarding switching the variables in the logic to accommodate for this case, as you mentioned above:

> I can't think of any other case where someone would supply both and prefer the personal license, other than PRs with no access to the secrets vs PRs with access to secrets. As such, if you switched the order of the if / elif in the action, I'd just pass the license "straight".
> 
> Was that a deliberate design choice or just something that happened coincidentally? Am I missing another use case?

This wasn't deliberate beyond it being defensive programming; a pro license has to also be returned so that it doesn't get locked as in use.

While I applaud the creativity for switching it around, semantically it isn't a sound solution (as it disables the other case) and it'd have to be done in test-runner and unity-builder as well, as they use exactly the same script.

That said, we're looking to combine all the logic in a CLI (see [roadmap](https://github.com/orgs/game-ci/projects/4/views/1)). I'll take your thoughts under advisement while working on that.

**Comment by mikeage** [comment]
Duplication is not an option for me. The second looks good, and I'd recommend it to others over my hack.

**Comment by mikeage** [comment]
Needing to return the pro license is a good point. Sensible choice.
