### ISSUE TITLE
Not updated DockerImage

### ISSUE THREAD

**Issue by m21-cerutti** [game-ci/unity-activate#67]
```
Run game-ci/unity-activate@v1.3
  with:
    unityVersion: 2020.3.6f1
/usr/bin/docker build /home/runner/work/_actions/game-ci/unity-activate/v1.3/action --file /home/runner/work/_actions/game-ci/unity-activate/v1.3/action/Dockerfile --build-arg IMAGE=gableroux/unity3d:2020.3.6f1 --tag unity-action:2020.3.6f1
Sending build context to Docker daemon  135.2kB

Step 1/12 : ARG IMAGE
Step 2/12 : FROM $IMAGE
manifest for gableroux/unity3d:2020.3.6f1 not found: manifest unknown: manifest unknown
Error: The process '/usr/bin/docker' failed with exit code 1
```
Seems that the change to unityci/editor have not been done yet.

**Comment by webbertakken** [comment]
For newer images you will need to switch to `v2` of the actions.

Under the hood `v2` images will be using `unityci/editor` images.

Since the activate step is also included in the `test-runner` and `builder` actions, there are not many people using this separate action, so nobody has taken the time to update this specific action to v2.

Recommend either using the other actions, or sending a PR to also update this action to use the new images.
